Promo
Rentality-xyz/Rentality-demo-contracts pull request #16
Opened 2024-12-31 14:09 UTC by HlibProtasov

2024-12-31 14:36 UTC, ArtemIslamovEM requested changes

2024-12-31 14:36 UTC, ArtemIslamovEM commented on hardhat.config.js
прибери ці правки

2024-12-31 14:36 UTC, ArtemIslamovEM commented on contracts/libs/RentalityTripsQuery.sol
наче нічого не помінялося

2024-12-31 14:36 UTC, ArtemIslamovEM commented on scripts/addressesContractsTestnets.v0_2_0.json
наче нічого не помінялося

2024-12-31 14:36 UTC, ArtemIslamovEM commented on promo/freePromo.txt
це порожні файли? нащо?

2024-12-31 14:36 UTC, ArtemIslamovEM commented on promo/nintyPromo.txt
це порожні файли? нащо?

2024-12-31 14:36 UTC, ArtemIslamovEM commented on promo/twentyPromo.txt
це порожні файли? нащо?

2024-12-31 14:36 UTC, ArtemIslamovEM commented on contracts/features/RentalityPromo.sol
> +function getPromoData(string memory promo) public view returns(Schemas.Promo memory) {
давай може додамо поки щоб тільки адмін міг подивитися їх

2024-12-31 14:36 UTC, ArtemIslamovEM commented on contracts/features/RentalityPromo.sol
> +function getPromoCodes() public view returns(string[] memory) {
давай може додамо поки щоб тільки адмін міг подивитися їх

2024-12-31 14:36 UTC, ArtemIslamovEM commented on contracts/features/RentalityPromo.sol
> +        break;
не бачу щоб exists мінялося. може помилка?

2024-12-31 14:47 UTC, HlibProtasov commented on promo/nintyPromo.txt
щоб після генерації в них були промокоди
і їх можна було передати для друку

2024-12-31 14:57 UTC, ArtemIslamovEM commented on promo/nintyPromo.txt
добре

2025-01-02 08:59 UTC, ArtemIslamovEM approved these changes

2025-01-02 08:59 UTC, merged